# Generated by Django 4.0.3 on 2022-05-10 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0003_blogsmodel_delete_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
